return {
  { "iamcco/markdown-preview.nvim", enabled = false },
  { "madox2/vim-ai", enabled = true },
  { "folke/flash.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "ggandor/leap.nvim", enabled = true },
  { "nvim-tree/nvim-tree.lua", enabled = true },
  { "nanozuki/tabby.nvim", enabled = false },
  { "akinsho/toggleterm.nvim", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "ThePrimeagen/harpoon", enabled = true },
  { "nvim-tree/nvim-tree.lua", enabled = false },
}
